### ISSUE TITLE
handle 401 response status codes by raising NotAuthenticatedError

### ISSUE THREAD

**Issue by ghost** [simplworld/simpl-client#8]
Currently, pip installing simpl-modelservice 0.9.0 results in this warning:
`genericclient-aiohttp 1.3.1 has requirement aiohttp<3.6,>=3.5, but you'll have aiohttp 3.6.2 which is incompatible.`

This appears to have no adverse effect on running the model service though.

**Comment by janeeisenstein** [comment]
Will need to upgrade, once `genericclient-requests` has been updated to properly handle 401 response status codes.

See: https://github.com/genericclient/genericclient-requests/issues/13

**Comment by janeeisenstein** [comment]
Fixed in v0.8.1.
